version: 0.2

phases:
  pre_build:
    commands:
      - echo ${AWS_ACCOUNT_ID}

  build:
    commands:
      - echo Build started on `date`
      - echo Pushing docker image to ECR
      - docker build -t shyaminayesh:hello .