name: ghcr-publish
on: [ push, workflow_dispatch ]

jobs:

  ghcr-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login (GHCR)
        uses: docker/login-action@v1
        with:
         registry: ghcr.io
         username: ${{ github.actor }}
         password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        run:
          docker build . --tag ghcr.io/shyaminayesh/hello-go:latest
